### ISSUE TITLE
Error: get_secret failed

### ISSUE THREAD

**Issue by Pavlo9999** [meldron/psonoci#1]
Caused by:
    0: get secret api call failed
    1: make request failed
    2: 400 Bad Request: Bad Request

**Comment by Pavlo9999** [comment]
1. Created API key.
![image](https://user-images.githubusercontent.com/33752651/197716614-eb90ab4d-5a47-4618-a32a-c31aa1c04574.png)
2. Installed psonoci  - version 0.3.0
3. Created test script:
![image](https://user-images.githubusercontent.com/33752651/197717137-caf4e6d9-3207-4194-94a7-55df901f6db6.png)
![image](https://user-images.githubusercontent.com/33752651/197715493-1e864d51-3eac-446c-886b-c2a7052efa60.png)

**Comment by Pavlo9999** [comment]
Also in the log file, I found 
[25/Oct/2022:08:05:56 +0000] "POST /server/api-key-access/secret/ HTTP/1.1" 400 16 "-" "psonoci/0.3.0" "-"

**Comment by meldron** [comment]
Hi @Pavlo9999,

I think the problem is that the `Link to the entry` value is not the `SECRET_ID`.

After you created your API key and added the secrets, you can open the `Edit API Key` view and there you will find the ids `psonoci` needs to access the secrets.

![image](https://user-images.githubusercontent.com/5972779/197721113-7661d164-6788-4f9a-8772-f9c98eaa8e03.png)

Please let me know if this doesn't help.

**Comment by Pavlo9999** [comment]
Fixed

**Comment by Pavlo9999** [comment]
@meldron yes, it was the issue, thank you for your help.
